# Generated by Django 4.2.27 on 2025-12-07 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('kodeGejala', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('namaGejala', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Gejala',
            },
        ),
        migrations.CreateModel(
            name='Kondisi',
            fields=[
                ('kodeKondisi', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('namaKondisi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('solusi', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Kondisi',
            },
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPengguna', models.CharField(help_text='Nama Pengguna untuk akses Pasien/Wali', max_length=50, unique=True)),
                ('kataSandi', models.CharField(max_length=128)),
                ('nama', models.CharField(max_length=100)),
                ('jenisKelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('tanggalLahir', models.DateField()),
                ('namaWali', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Wali/Orang Tua')),
                ('nomorTelepon', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pasien',
            },
        ),
        migrations.CreateModel(
            name='PengukuranFisik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggalUkur', models.DateField()),
                ('beratBadan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Berat Badan (kg)')),
                ('tinggiBadan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tinggi/Panjang Badan (cm)')),
                ('skor_Z_BB_U', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Z-Score BB/U')),
                ('skor_Z_TB_U', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Z-Score TB/U')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pasien')),
            ],
            options={
                'verbose_name_plural': 'Pengukuran Fisik',
                'ordering': ['tanggalUkur'],
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('jadwalNotifikasi', models.DateTimeField()),
                ('sudahTerkirim', models.BooleanField(default=False, verbose_name='Sudah Terkirim')),
                ('tipe', models.CharField(default='pengukuran_ulang', max_length=50)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pasien')),
            ],
            options={
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-jadwalNotifikasi'],
            },
        ),
        migrations.CreateModel(
            name='Konsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggalKonsultasi', models.DateTimeField(auto_now_add=True)),
                ('hasilKondisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kondisi', verbose_name='Hasil Diagnosa')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pasien')),
            ],
            options={
                'verbose_name_plural': 'Konsultasi',
            },
        ),
        migrations.CreateModel(
            name='DetailKonsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gejala')),
                ('konsultasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konsultasi')),
            ],
            options={
                'verbose_name_plural': 'Detail Konsultasi',
                'unique_together': {('konsultasi', 'gejala')},
            },
        ),
        migrations.CreateModel(
            name='Aturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeKelompokAturan', models.CharField(help_text='Kode Kelompok Aturan (misal: R01).', max_length=10)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gejala')),
                ('kondisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kondisi')),
            ],
            options={
                'verbose_name_plural': 'Aturan Basis Pengetahuan',
                'unique_together': {('kondisi', 'gejala', 'kodeKelompokAturan')},
            },
        ),
    ]
