# Generated by Django 4.2.27 on 2025-12-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengukuranfisik',
            name='imunisasi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Imunisasi'),
        ),
        migrations.AddField(
            model_name='pengukuranfisik',
            name='lingkarKepala',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lingkar Kepala (cm)'),
        ),
        migrations.AddField(
            model_name='pengukuranfisik',
            name='lingkarLengan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lingkar Lengan Atas (cm)'),
        ),
    ]
