# Generated by Django 4.2.27 on 2025-12-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pengukuranfisik_imunisasi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifikasi',
            options={'ordering': ['-jadwalNotifikasi'], 'verbose_name_plural': 'Daftar Notifikasi'},
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='sudahTerkirim',
            field=models.BooleanField(default=False, verbose_name='Sudah Dibaca'),
        ),
    ]
